# Generated by Django 3.1.3 on 2020-12-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20201129_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='label',
            field=models.CharField(max_length=25),
        ),
    ]
