# Generated by Django 3.1.3 on 2021-01-22 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_auto_20201202_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='levelupapi.event'),
        ),
        migrations.AlterField(
            model_name='gamerevent',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='levelupapi.gamer'),
        ),
    ]
